pipelines:
  - pipeline: form
    name: 2_debug
    fuse_imu: true
    point_feats_per_sector: 0

  # - pipeline: form
  #   name: lo
  #   point_feats_per_sector: 0

datasets:
  - name: newer_college_2020/short_experiment
    length: 2000
