pipelines:
  - pipeline: form
    name: revert_prior_values
    # point_feats_per_sector: 0

datasets:
  - name: oxford_spires/blenheim_palace_02
    length: 6000
  # - name: oxford_spires_custom/blenheim_palace_02
  #   length: 6000
  - name: newer_college_2020/short_experiment
    length: 2000